本文介绍单个物种的种群动态。为了方便起见，我们只考虑无个体迁入或迁出的*封闭种群*。该种群大小因个体出生而增长，因个体死亡而缩小。若种群增长不受抑制，则其增长呈指数型。无论种群大小变化，其出生率和死亡率均不变。已知人均出生率（per-capita birth rate）为$b$， 人均死亡率（per-capita death rate）为$d$， 则种群大小$N$的变化为：

$$\frac{dN}{dT} = bN - dN = (b-d)N$$

$(b-d)$ 是一个常数，可合并写为自然增长率(intrinsic growth rate)$r$。则指数型增长可写为：

$$\frac{dN}{dT} = rN$$

对于一个指数型增长的种群，其种群大小随时间变化的轨迹呈J型曲线。而J的形状由$r$的数值决定。👇请使用文末的app探索$r$值如何改变种群的轨迹。

#### *限制种群增长*
上文的指数增长模型（exponential growth model）预测，该类种群的长期规模会趋于无穷大。但现实中，没有种群的数量能够无限制增长，因此指数增长模型可以被改进。 

指数增长模型的前提条件是人均出生率$b$和人均死亡率$d$均不变。我们可以放宽这个条件，并假设当种群的增长趋于环境承载力(carrying capacity $K$)时，其总增长率(net growth rate $rD$)呈线性递减。此类种群的动态变化可用逻辑斯谛增长(logistic growth)模型描述：

$$\frac{dN_i}{dt} = r_iN_i \left(1-\frac{N_i}{K_i}\right)$$

呈逻辑斯谛增长的种群的会持续增长，直到种群规模与环境承载力相等($N_i = K_i$)。当种群规模超出环境承载力时，种群出现负增长，直到其规模减少至环境承载力。

#### *滞后逻辑斯谛增长* 

在某些情况下，一个种群的增长率会取决于该种群在过去某个时间点的规模。比如，生物的繁殖产量会与其未成年时资源竞争的强度相关。对于这种情况，某时间点$t$时的种群增长率可以用过去$t-\tau$时的种群大小表示：  

$$  \frac{dN_i}{dt} = r_iN_{i,t} \left(1-\frac{N_{i,t-\tau}}{K_i}\right)$$
在app中可选择密度制约，并请勾选“Lagged density dependence”（滞后的密度依赖）选项，来模拟滞后逻辑斯谛增长。


#### *参数表*
```{r parameter descriptions ch, echo = F}
pars_vars <- c("$r_i$", 
               "$K_i$", 
               "$N_i$",
               "$\\tau$")
descriptions <- c("物种$i$的自然增长率",
                 "物种$i$的环境承载力（carrying capacity）",
                 "物种$i$的种群大小",
                 "滞后逻辑斯谛增长的滞后时间")
param_df <- data.frame(pars_vars, descriptions)
kable(x = param_df, format = "html", 
      col.names = c("参数/变量", "描述")) %>%
  kable_styling(full_width = FALSE, 
                bootstrap_options = c("striped", "hover", "condensed"),
                position = "center")
```

