### Biogeografía de Islas

La teoría de Biogeografía de Islas, articulada por primera vez por Robert MacArthur y E.O. Wilson en el artículo de 1964, "[Equilibrium theory of insular zoogeography](https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.1558-5646.1963.tb03295.x)", presenta un enfoque cuantitativo y productivo hacia la comprensión de la biodiversidad en sistemas insulares. La teoría está construida en base a las ideas de inmigración y extinción, dos procesos centrales que determinan la diversidad de especie en islas y que varían de una manera predecible. Específicamente, se espera que la tasa de inmigración desde el continente sea mayor en islas cercanas, en comparación con la tasa de inmigración hacia islas lejanas, y que las tasas de extinción sean mayores en islas pequeñas, en comparación con islas de mayor tamaño. El balance entre estos dos procesos (inmigración y extinción) determina el equilibrio en la riqueza de especies. MacArthur y Wilson expandieron esta teoría en su libro clásico de 1967, "[The Theory of Island Biogeography](https://en.wikipedia.org/wiki/The_Theory_of_Island_Biogeography)". Daniel Simberloff [condujo tests experimentales notables](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.2307/1934856) de esta teoría usando islas de manglares en Florida, y la teoría de biogeografía de islas también ha sido muy influyente en [biología de la conservación](https://www.jstor.org/stable/1742652). Para una revisión reciente de la influencia de la teoría de biogeografía de islas en el campo de la ecología, escrita por su 50 aniversario, ver [este artículo](https://science.sciencemag.org/content/357/6354/eaam8326).

Tasa de extinción en la isla:
$$E = e^{\frac{kS}{A}}-1$$
Tasa de inmigración desde el continente hacia la isla: 
$$I = e^{\left(-\frac{k}{D}*(S-M)\right)}-1$$
Número de especies en una isla en equilibrio:  
$$S_{eq} = \frac{AM}{D+A}$$

donde:

- $D$ es la distancia entre el continente y la isla (km);  
- $A$ es el área de la isla (km^2);  
- $M$ es el número de especies en el continente; 
- $k$ is un factor de escala arbitrario ($k=0.15$ en esta aplicación).


```{r app-es}
sidebarLayout(
        sidebarPanel(
            sliderInput(inputId = "D1_es",
                        label = HTML("D<sub>A</sub> (distancia entre el continente y la isla A)"),
                        min = 1,
                        max = 8,
                        value = 1),
            sliderInput(inputId = "D2_es",
                        label = HTML("D<sub>B</sub> (distancia entre el continente y la isla B)"),
                        min = 1,
                        max = 8,
                        value = 4),            
            sliderInput(inputId = "A1_es",
                        label = HTML("A<sub>A</sub> (área de la isla A)"),
                        min = .1,
                        max = 4,
                        value = 1),
            sliderInput(inputId = "A2_es",
                        label = HTML("A<sub>B</sub> (área de la isla B)"),
                        min = .1,
                        max = 4,
                        value = .5),
            sliderInput(inputId = "M_es",
                        label = "M (número de especies en el continente)",
                        min = 1,
                        max = 100,
                        value = 100),
            width=4),
        mainPanel(
            renderPlot({plot_to_print_es()}, width = 400, height = 600)
        )
)

Dvec_es <- reactive({c(input$D1_es, input$D2_es)})
Avec_es <- reactive({c(input$A1_es, input$A2_es)})
plots_es <- reactive({
  ecoevoapps::run_ibiogeo_model(D = Dvec_es(), A = Avec_es(), M=input$M_es, k=0.015)
})

map_es <- reactive({plots_es()$map} + 
  ylab("distancia entre el continente y la isla (km)"))
eq_plot_es <- reactive({plots_es()$eq_plot} +
  ylab("Tasa de inmigración/extinción\n(especies por año)") + 
    xlab("\nNúmero de especies en las islas")) 

plot_to_print_es <- reactive({
  map_es() / eq_plot_es()
})


```

*Translated into Español by Rosa McGuire*

### Referencias:

"[Equilibrium theory of insular zoogeography](https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.1558-5646.1963.tb03295.x)", Macarthur and Wilson 1964.  

"[The Theory of Island Biogeography](https://en.wikipedia.org/wiki/The_Theory_of_Island_Biogeography)", Macarthur and Wilson 1967. 

"[Experimental Zoogeography of Islands: The Colonization of Empty Islands](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.2307/1934856)", Simberloff and Wilson 1969.  

"[Island biogeography: Taking the long view of nature’s laboratories](https://science.sciencemag.org/content/357/6354/eaam8326)", Whittaker et al. 2017. 

"[Island Biogeography and Conservation: Strategy and Limitations](https://www.jstor.org/stable/1742652)", Diamond et al. 1976. 
