---
title: "Island Biogeography"
author: "Marcel Vaz"
output:
  html_document:
    theme: united
    toc: true
    toc_depth: 3
runtime: shiny
---

Extinction rate on island:
$$E = e^{\frac{kS}{A}}-1$$
Immigration rate from mainland to island:
$$I = e^{\left(-\frac{k}{D}*(S-M)\right)}-1$$
Equilibrium number of species on the island:  
$$S_{eq} = \frac{AM}{D+A}$$

where:

- $D$ is the distance from the mainland to the island (km);  
- $A$ is the area of the island (km^2);  
- $M$ is the number of species on the mainland;  
- $k$ is the scaling constant (set to $k=0.15$ in this app).
```{r, include = F}
library(ggplot2)
library(dplyr)
library(ecoevoapps)
library(patchwork)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# source("functions.R")
source("ibiogeo_constants.R")
```

```{r}
sidebarLayout(
        sidebarPanel(
            sliderInput(inputId = "D1",
                        label = "Distance from mainland (Island A)",
                        min = 1,
                        max = 8,
                        value = 1),
            sliderInput(inputId = "D2",
                        label = "Distance from mainland (Island B)",
                        min = 1,
                        max = 8,
                        value = 4),            
            sliderInput(inputId = "A1",
                        label = "Area of island A",
                        min = .1,
                        max = 4,
                        value = 1),
            sliderInput(inputId = "A2",
                        label = "Area of island B",
                        min = .1,
                        max = 4,
                        value = .5),
            sliderInput(inputId = "M",
                        label = "Number of species in the mainland",
                        min = 1,
                        max = 100,
                        value = 100),
            width=4),
        mainPanel(
            renderPlot({plot_to_print()}, width = 400, height = 600)
        )
)

Dvec <- reactive({c(input$D1, input$D2)})
Avec <- reactive({c(input$A1, input$A2)})
map <- reactive({
  # generate "map" of islands
  make_islands_map(tx = tx, ty = ty, txa = txa, tya = tya,
                   txb = txb, tyb = tyb, D = Dvec(), 
                   A = Avec(), M=input$M, k=0.015)
  
})

eq_plot <- reactive({
  # generate plot that shows equilibrium species number
  make_equilibrium_plot(D = Dvec(), A = Avec(), M = input$M, k = k)
})

plot_to_print <- reactive({
  map() / eq_plot()
})

```
