---
title: "Discrete population growth models"
author: "Gaurav Kandlikar"
date: "4/12/2020"
output:
  html_document:
    theme: united
    toc: true
    toc_depth: 3
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(ggplot2)
library(deSolve)
library(ecoevoapps)
library(patchwork)
library(latex2exp)
theme_set(ecoevoapps::theme_apps())
```

## Discrete exponential growth 

$N_{t+1} = \lambda N_t$

```{r exponential-logistic, echo=FALSE}
sidebarLayout(
  sidebarPanel(
    # User defined lambda -------
    sliderInput("lambda", label = "Population growth rate (lambda):",
                min = 0.01, max = 2, value = 1.2, step = .01),
    # User defined N0 -------
    numericInput("N0", label = "Initial population size (N0)",
                min = 1, max = 100, value = 1),
    # User defined time ---------
    numericInput("time", label = "Number of time steps to project",
                min = 1, max = 1000, value = 30)
    ),

  # Panel of plots -----
  mainPanel(
    renderPlot({plots_to_print()}, width = 450, height = 450)
  )
)

# Generate trajectories for sp 1 --------
exponential_pop_traj <- reactive({discrete_exponential(N0 = input$N0, 
                                                       lambda = input$lambda,
                                                       time = input$time)})
exponential_pop_df <- reactive({data.frame(time = 0:input$time,
                                 Nt= exponential_pop_traj(),
                                 popdiff = c(NA, diff(exponential_pop_traj())),
                                 Ntm1 = c(lag(exponential_pop_traj())),
                                 popratio = exponential_pop_traj()/lag(exponential_pop_traj()))})


# Make plot caption -------------
plot_caption_exp <- reactive({
    latex2exp::TeX(paste0("Parameter values: $\\lambda = $", input$lambda))
})


# Make plot -----------
trajaectory_plot <- reactive({ggplot(data.frame(exponential_pop_df())) +
  geom_line(aes(y = Nt, x = time), size = .2) +
    geom_point(aes(y = Nt, x = time), size = 5, shape = 21,
               fill = "white", stroke = 0) +
    geom_point(aes(y = Nt, x = time), size = 2, shape = 21,
               fill = "white", stroke = .8) +
    ylab(latex2exp::TeX("Population size at time $t$ ($N_t$)"))})

# Make a list of plots  ----
plots_to_print <- reactive({trajaectory_plot() +
    labs(caption = plot_caption_exp(),
         title = "Population growth with the discrete exponential model")})

```

## Discrete logistic growth  {.tabset}

### Standard discrete logistic model

$N_{t+1} = r_dN_t\left(1-\frac{N_t}{K}\right)$

```{r discrete-logistic, echo=FALSE}
sidebarLayout(
  sidebarPanel(
    # User defined lambda -------
    sliderInput("rd_dl", label = "Population growth rate (rd):",
                min = 0.01, max = 3, value = 1.01, step = .01),
    # User defined N0 -------
    numericInput("N0_dl", label = "Initial population size (N0)",
                min = 1, max = 100, value = 1),
    # User defined carrying capacity (K) ----------    
    numericInput("K_dl", label = "Carrying capacity",
                 min = 1, max = 1000, value = 100),
    # User defined time ---------
    numericInput("time_dl", label = "Number of time steps to project",
                min = 1, max = 1000, value = 30)

    ),

  # Panel of plots -----
  mainPanel(
    renderPlot({plots_to_print_dl()}, width = 450, height = 800)
  )
)

# Get user defined parameters for discrete logistic  ------
dl_pop_traj <- reactive({discrete_logistic(N0 = input$N0_dl, K = input$K_dl, 
                                           rd = input$rd_dl, time = input$time_dl)})
dl_df <- reactive({data.frame(Nt = dl_pop_traj(),
                      time = 1:input$time_dl,
                      Ntm1 = lag(dl_pop_traj()))})

# Generate trajectories for discrete logistic --------
trajaectory_plot_dl <- reactive({ggplot(dl_df()) +
    geom_line(aes(x = time, y = Nt), size = .2) +
    geom_point(aes(y = Nt, x = time), size = 5, shape = 21,
               fill = "white", stroke = 0) +
    geom_point(aes(x = time, y = Nt), size = 2, shape = 21,
               fill = "white", stroke = .8 ) +
    labs(title = "Population growth with the discrete logistic model")})

# cobweb for standard discrete logistic model -----
cobweb_dl <- reactive({ggplot(dl_df(), aes(x = Ntm1)) +
    stat_function(fun = function(x) discretelogistic_eqn(x, input$rd_dl, input$K_dl)) +
    geom_hline(yintercept = input$K_dl, size = .2)+
    geom_vline(xintercept = input$K_dl, size = .2) +
    ylab(TeX("$N_{t+1}"))+
    xlab(TeX("$N_t$")) +
    labs(title = "Cobweb plot")})

# Make plot caption ----
plot_caption_dl <- reactive({
    latex2exp::TeX(paste0("Parameter values: $r_d = $", input$rd_dl, "; K = ", input$K_dl))
})
# Make a list of plots  ----
plots_to_print_dl <- reactive({{trajaectory_plot_dl()/cobweb_dl()} + 
    labs(caption = plot_caption_dl())})
```

### Ricker model

$N_{t+1} = N_t e^{(r (1 - N_t/K))}$
```{r ricker-model, echo=FALSE}
sidebarLayout(
  sidebarPanel(
    # User defined lambda -------
    sliderInput("r_ricker", label = "Population growth rate (r):",
                min = 0.01, max = 3, value = 1.01, step = .01),
    # User defined N0 -------
    numericInput("N0_ricker", label = "Initial population size (N0)",
                min = 1, max = 100, value = 1),
    # User defined carrying capacity (K) ----------    
    numericInput("K_ricker", label = "Carrying capacity",
                 min = 1, max = 1000, value = 100),
    # User defined time ---------
    numericInput("time_ricker", label = "Number of time steps to project",
                min = 1, max = 1000, value = 30, step = 5)

    ),

  # Panel of plots -----
  mainPanel(
    renderPlot({plots_to_print_ricker()}, width = 450, height = 800)
  )
)

# Get user defined parameters for discrete logistic  ------
ricker_pop_traj <- reactive({ricker_model(N0 = input$N0_ricker, K = input$K_ricker, 
                                                 r = input$r_ricker, time = input$time_ricker)})
ricker_df <- reactive({data.frame(Nt = ricker_pop_traj(),
                      time = 1:input$time_ricker,
                      Ntm1 = lag(ricker_pop_traj()))})


# Generate trajectories for discrete logistic --------
trajaectory_plot_ricker <- reactive({ggplot(ricker_df()) +
    geom_line(aes(x = time, y = Nt), size = .2) +
    geom_point(aes(y = Nt, x = time), size = 5, shape = 21,
               fill = "white", stroke = 0) +
    geom_point(aes(x = time, y = Nt), size = 2, shape = 21,
               fill = "white", stroke = .8 ) + 
    labs(title = "Population growth with the Ricker model")})

# cobweb plot for ricker model -----
cobweb_ricker <- reactive({ggplot(ricker_df(), aes(Ntm1)) + 
    stat_function(fun = function(x) ricker_eqn(x, input$r_ricker, input$K_ricker)) + 
    geom_hline(yintercept = input$K_ricker, size = .2)+
    geom_vline(xintercept = input$K_ricker, size = .2) + 
    ylab(TeX("$N_{t+1}"))+
    xlab(TeX("$N_t$")) +
    labs(title = "Cobweb plot")})

# Make plot caption ----
plot_caption_ricker <- reactive({
    latex2exp::TeX(paste0("Parameter values: $r = $", input$r_ricker, "; K = ", input$K_ricker))
})

# Make a list of plots  ----

plots_to_print_ricker <- reactive({{trajaectory_plot_ricker()/cobweb_ricker()} + 
    labs(caption = plot_caption_ricker())})

```

### Beverton Holt model

$N_{t+1} = \frac{RN_t}{1+\left(\frac{R-1}{K}\right)N_t}$

```{r beverton-holt, echo=FALSE}
sidebarLayout(
  sidebarPanel(
    # User defined lambda -------
    sliderInput("r_bh", label = "Population growth rate (R):",
                min = 0.01, max = 3, value = 1.25, step = .01),
    # User defined N0 -------
    numericInput("N0_bh", label = "Initial population size (N0)",
                min = 1, max = 100, value = 1),
    # User defined carrying capacity (K) ----------    
    numericInput("K_bh", label = "Carrying capacity",
                 min = 1, max = 1000, value = 100),
    # User defined time ---------
    numericInput("time_bh", label = "Number of time steps to project",
                min = 1, max = 1000, value = 30, step = 5)

    ),

  # Panel of plots -----
  mainPanel(
    renderPlot({plots_to_print_bh()}, width = 450, height = 800)
  )
)

# Get user defined parameters for discrete logistic  ------
bh_pop_traj <- reactive({beverton_holt_model(N0 = input$N0_bh, K = input$K_bh, Rd = input$r_bh, time = input$time_bh)})
bh_df <- reactive({data.frame(Nt = bh_pop_traj(),
                      time = 1:input$time_bh,
                      Ntm1 = lag(bh_pop_traj()))})

# Generate trajectories for beverton-holt model --------
trajaectory_plot_bh <- reactive({ggplot(bh_df()) +
    geom_line(aes(x = time, y = Nt), size = .2) +
    geom_point(aes(y = Nt, x = time), size = 5, shape = 21,
               fill = "white", stroke = 0) +
    geom_point(aes(x = time, y = Nt), size = 2, shape = 21,
               fill = "white", stroke = .8 ) +
    labs(title = "Population growth with the Beverton-Holt model")})

# Generate cobweb for beverton-holt model --------
cobweb_bh <- reactive({ggplot(bh_df(), aes(Ntm1)) + 
    stat_function(fun = function(x) bevertonholt_eqn(x, input$r_bh, input$K_bh)) + 
    geom_hline(yintercept = input$K_bh, size = .2)+
    geom_vline(xintercept = input$K_bh, size = .2) + 
    ylab(TeX("$N_{t+1}"))+
    xlab(TeX("$N_t$")) +
    labs(title = "Cobweb plot")})

# Make plot caption ----
plot_caption_bh <- reactive({
    latex2exp::TeX(paste0("Parameter values: $r = $", input$r_bh, "; K = ", input$K_bh))
})

# Make a list of plots  ----

plots_to_print_bh <- reactive({{trajaectory_plot_bh()/cobweb_bh()} + 
    labs(caption = plot_caption_bh())})

```




