Tek bir türün popülasyon dinamiğini değerlendirelim. Analizimizi basitleştirmek amacıyla *kapalı bir popülasyon* ile başlayalım (kapalı popülasyonlar, göç almayan veya göç vermeyen popülasyanlardır). Popülasyon sadece doğumlar ile büyür ve ölümler ile küçülür. Geometrik olarak büyüyen bir popülasyonda, popülasyon kontrollü olarak büyümez, doğum ve ölüm oranları popülasyonun boyutuna rağmen stabildir. $b$’nin birey başına doğum oranı ve $d$’nin birey başına ölüm oranı olduğu bir popülasyonda, popülasyon boyutundaki ($N$) değişim şu şekilde belirtilir:

$$\frac{dN}{dT} = bN - dN = (b-d)N$$

$(b-d)$ farkının sabit olarak $r$ ile ifade edildiği geometrik popülasyon büyüme denklemi şu şekilde yazılır:

$$\frac{dN}{dT} = rN$$

Geometrik büyüyen bir popülasyon karakteristik bir J tipi büyüme gosterir. Bu üstel büyüme modelinde popülasyon boyutu zamana karşı grafiklendiğinde, $r$ sabiti J tipi büyümenin şeklini kontrol eder. $r$ sabitinin popülasyon boyutunun zamanda değişimini nasil etkilediğini gözlemlemek icin aşağıya inin!

#### *Popülasyon büyümesine limitler*
Geometrik artış modeli temel bir şekilde, uzun vadede popülasyonların sonsuz bir boyuta ulaşacağını öngörür. Doğada, popülasyonların sonsuz boyuta ulaşmadığını rahatlıkla gözlemliyoruz ve bu gerçeklik geometrik modelimizi geliştirmemiz gerektiğini gösteriyor. 

Geometrik modelin varsayımlarını tekrar gözden geçirelim: özellikle, b ($b$) ve d ($d$) oranlarının sürekli olarak sabit kaldığı temel varsayamını. Bu varsayımdan ödün vererek, net popülasyon büyüme oranının ($r$) popülasyon boyutunun taşıma kapasitesine ($K$) yaklaştığında lineer olarak azalmasına izin vererek (çevre direncini göze alarak) popülasyon modelimizi daha gerçekçi hale getirebiliriz. Sonucunda ortaya çıkan S tipi büyüme, lojistik popülasyon büyüme modeli, şu şekilde tanımlanır:

$$\frac{dN_i}{dt} = r_iN_i \left(1-\frac{N_i}{K_i}\right)$$

S tipi büyüme gösteren popülasyonlar popülasyon boyutu taşıma kapasitesine eşit olana kadar büyürler ($N_i = K_i$) (pozitif popülasyon büyüme oranına sahip olabilirler). Popülasyon boyutu taşıma kapasitesini geçtiği anda, popülasyon büyüme oranı negatif olur, ve popülasyon boyutu taşıma kapasitesine geri düşer. 

#### *Gecikmeli lojistik büyüme*

Bazı durumlarda, popülasyonun büyüme oranı geçmiş zamandaki popülasyon boyutuna bağlı olabilir. Örnek olarak, popülasyonların doğum kapasitesi yetişkin olmayan fertlerin doğal kaynaklar için ne kadar rekabet etmesi gerektiğine bağlıdır. Böyle bir senaryoyu $t$ zamanındaki popülasyon büyüme oranını $t-\tau$ nın fonksiyonu halinde belirtebiliriz: 

$$  \frac{dN_i}{dt} = r_iN_{i,t} \left(1-\frac{N_{i,t-\tau}}{K_i}\right)$$
Gecikmeli lojistik büyümenin sonuçlarını S tipi büyüme simülasyonunun “gecikmeli büyüme” opsiyonuyla gözlemleyebilirsiniz. 



#### *Parametre tablosu*
```{r parameter descriptions turkish, echo = F}
pars_vars <- c("$r_i$", 
               "$K_i$", 
               "$N_i$",
               "$\\tau$")
descriptions <- c("$i$ turunun net popülasyon büyüme oranı",
                 "$i$ turunun tasima kapasitesi",
                 "$i$ turunun populasyon boyutu",
                 "Gecikmeli lojistik buyumede gecikme suresi")
param_df <- data.frame(pars_vars, descriptions)
kable(x = param_df, format = "html", 
      col.names = c("Parametre/ Degisken", "Aciklama")) %>%
  kable_styling(full_width = FALSE, 
                bootstrap_options = c("striped", "hover", "condensed"),
                position = "center")
```

*Translated into Turkish by Damla Cinoglu*

