---
title: 'Consumer-Resource Interactions: Type II Functional Response'
author: "Rosa M. McGuire"
date: "5/27/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(deSolve)
library(tidyverse)
library(patchwork)

# Consumer Resource Models: Type II Functional Response

lv_pred2 <- function(time,init,pars) {
  with (as.list(c(time,init,pars)), {
    # description of parameters:
    # r = per capita growth rate (prey)
    # a = attack rate 
    # T_h = handling time
    # e = conversion efficiency
    # d = predator death rate 
    
    dH_dt = r*H - (a*H*P)/(1 + a*T_h*H)
    dP_dt = e*(a*H*P)/(1 + a*T_h*H) - d*P
    return(list(c(dH = dH_dt, dP = dP_dt)))
  
  })
}

```

## Type II Functional Response  

\[
\begin{eqnarray}
\frac{dH}{dt} = rH - \frac{aH}{1+aT_hH} P\\
\\
\frac{dP}{dt} = eP \frac{aH}{1+aT_hH} - dP
\end{eqnarray}
\]

Where:

* $H =$ Prey population size
* $P =$ Predator population size
* $r =$ per capita growth rate of Prey
* $a =$ Predator attack rate
* $T_h =$ Predator handling time
* $e =$ conversion efficiency
* $d =$ Predator death rate  

```{r eruptions, echo=FALSE}
sidebarLayout(
  sidebarPanel(
    ### Ask users for parameter values ----
    ## r, a, T_h, e, d
    
    sliderInput("r", label = "Per capita growth rate of Prey", min = .0001, max = 1.0, value = .5),
    sliderInput("a", label = "Predator attack rate", min = .001, max = 1.0, value = .1),
    sliderInput("T_h", label = "Predator handling time", min = 0.001, max = 1.0, value = 0.2),
    sliderInput("e", label = "Predator conversion efficiency", min = .001, max = 1.0, value = 1),
    sliderInput("d", label = "Per capita death rate of Predator", min = .0001, max = 1.0, value = .3),
    
    
      
    ### Ask users for initial conditions -----
    #N1, N2
    
    numericInput("H", label = "Initial population size of Prey", min = 1, value = 10),
    numericInput("P", label = "Initial population size of Predator", min = 1, value = 10),
    
    ### Ask users for time to simulate ----
    
    
    numericInput("t", label = "Timesteps", min = 1, value = 100),
    
  ),  
  
 
  mainPanel(renderPlot(lvpred2_plot()),renderPlot(lvpred2_np())),
  
  #mainPanel(renderPlot(lvpred2_np()))
)

 # Set the initial population sizes

init <- reactive({c(H = input$H , P = input$P)})

# Set the parameter values

    # description of parameters:
    # r = per capita growth rate (prey)
    # a = attack rate 
    # T_h = handling time
    # e = conversion efficiency
    # d = predator death rate 

pars <- reactive({c(r = input$r, a = input$a , T_h = input$T_h , e = input$e , d = input$d )})

# Time over which to simulate model dynamics
time <- reactive({seq(0,input$t,by = .1)})



# Use the lv_competition function above to run 
# the lotka-volterra competition model using the 
# parameter estimates defined above

lv_pred2_out <- reactive({data.frame(deSolve::ode(func = lv_pred2, y = init(), parms = pars(), times = time()))})
  

# Reshape the data so that population sizes of both 
# species are in one column, and an extra column to define
# species name. This helps with the plotting...

lv_pred2_out_long <- reactive({pivot_longer(lv_pred2_out(), c(H,P), "Population")})


# Plots
lvpred2_plot <- reactive({ggplot(lv_pred2_out_long()) + 
  geom_line(aes(x = time, y = value, color = Population), size = 2) + 
  scale_color_brewer(palette = "Set1") +
  ylab("Population size")  })

lvpred2_np <- reactive(plot(lv_pred2_out()$H, lv_pred2_out()$P, type='l',xlab="Number of Prey",ylab="Number of Predators"))


   
```

