---
title: "Pulliam source-sink metapopulation model"
author: "Xinyi Yan"
date: "May 17, 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Pulliam source-sink metapopulation model
#library(deSolve)
library(tidyverse)
#library(phaseR)

# Write a function to calculate Nt+1 for both populations, using DISCRETE time
source_sink <- function(endtime,init,params) {
  with (as.list(c(endtime,init,params)), {
    # description of parameters/state variables:
    # pa = probability of adults surviving winter
    # pj = probability of juvenile surviving winter
    # beta1 = fecundity of population 1
    # beta2 = fecundity of population 2
    # n1 <- population of n1 (source by default)
    # N1 <- limiting breeding site for source population (equilibrium source population)
    # n2 <- population of n2 (sink by default)
    # assume sink population has unlimited breeding sites, equilibirum N2 will be calculated
    # when all breading sites are occupied, emigration happens
    
    n1 <- numeric(endtime)
    n2 <- numeric(endtime)
    e <- 0 # before breeding sites are all occupied at the source, emmigration is 0
    
    n1[1] <- n10
    n2[1] <- n20
    
    for (t in 2:endtime) {
      # at the start of the year, population = end of last year
      n10 <- n1[t-1]
      n20 <- n2[t-1]

      # growth cycle  of the year
      n1[t] <- n10*(pa + pj*beta1) 
      n2[t] <- n20*(pa + pj*beta2)
      # optional: rounding, keep populations integers 
      # n1[t] <- round( n1[t])
      # n2[t] <- round( n2[t])
      
      # migration cycle of the year
      if (n1[t] >= N1){
        
        e <- n1[t] - N1 #emmigration away from source, to sink
      }
      n1[t] <- n1[t] - e 
      n2[t] <- n2[t] + e
    }
    # return both n1 and n2
    return(list(n1, n2))
  })
}

```

Extra feature: double check if labmda 1 > 1 and labmda 2 < 1
```{r eruptions, echo=FALSE}

sidebarLayout(
  sidebarPanel(
    ### ask for params (model parameters)
    ### params <- c(pa = .7, pj = .2, beta1 = 3, beta2 = 1, N1 = 300) 
    sliderInput("pa", label = "Probability of adults surviving winter", min = 0, max = 1, value = .7),
    sliderInput("pj", label = "Probability of juveniles surviving winter", min = 0, max = 1, value = .2),
    sliderInput("beta1", label = "Fecundity at the source site", min = 0, max = 100, value = 3),
    sliderInput("beta2", label = "Fecundity at the sink site", min = 0, max = 50, value = 1),
    numericInput("N1", label = "maximum breeding sites at source", min = 1, value = 300),
    
    ### ask for init (inital conditions)
    ### init <- c(N = 20, P = 2)
    numericInput("n10",label = "initial population at source", min = 0, value = 110),
    numericInput("n20",label = "initial population at sink", min = 0, value = 100),
    
    ### ask for time (time to simulate)
    numericInput("endtime", label = "years to simulate", min = 2, value = 50)
  ),
  
  mainPanel(renderPlot(ss_plot()))
)


# Set the initial population sizes
#init <- c(n10 = 110, n20 = 100)
#any time it's reactive, it has to be {} in ()
init <- reactive({ c(n10 = input$n10, n20 = input$n20)}) 

# Set the parameter values
#params <- c(pa = .7, pj = .2, beta1 = 3, beta2 = 1, N1 = 300) 
params <- reactive({ c(pa = input$pa, pj = input$pj, 
                       beta1 = input$beta1, beta2 = input$beta2, N1 = input$N1) })
# Time over which to simulate model dynamics
time <- reactive({ endtime = input$endtime })

#now init and params are reactive, use them like functions "xx()"
ss_df <- reactive({ data.frame(year = 1:time(), 
                              source_sink(endtime = time(), init = init(), 
                                            params = params())) })
ss_out <- reactive({
   out <- ss_df()
   colnames(out) <- c("year", "source", "sink")
   out
 })

ss_out_long <- reactive({ pivot_longer(ss_out(), c(source,sink), "population") })

# Plot
ss_plot <- reactive({ ggplot(ss_out_long()) + 
  geom_line(aes(x = year, y = value, color = population), size = 2) + 
  scale_color_brewer(palette = "Set1") +
  ylab("Population size")  })

```
