---
title: "Infectious disease models"
author: "Madeline Cowen"
date: "April 29, 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# library(tidyverse)
library(ggplot2)
library(tidyr)
library(purrr)
library(dplyr)
library(deSolve)
library(ecoevoapps)
library(patchwork)

includeMarkdown("SIR_overview.md")
```

# Disease Models {.tabset}
## SIR model

```{r SIR app, echo=FALSE}
sidebarLayout(
  
  sidebarPanel(
    
    ### Ask user for parameter values ----
    
    #m - death/birth rate
    #beta - infection rate
    #gamma - recovery rate
    #v - vaccination rate
    
    sliderInput("m", label = "Birth/Death rate:",
                min = 0, max = 1, value = .1, step = 0.1),
    
    sliderInput("beta", label = "Infection rate:",
                min = 0, max = 1, value = .01, step = 0.01),
    
    sliderInput("gamma", label = "Recovery rate:",
                min = 0, max = 1, value = .2, step = 0.1),
    
    sliderInput("v", label = "Vaccination rate:",
                min = 0, max = 1, value = 0, step = 0.1),
    
    ### Ask user for initial conditions ----
    numericInput("S0", label = "Initial population size of S", min = 0, value = 100),
    numericInput("I0", label = "Initial population size of I", min = 0, value = 1),
    numericInput("R0", label = "Initial population size of R", min = 0, value = 0),
    
    ### Ask user for time to simulate ----
    numericInput("time", label = "Time to simulate", min = 10, value = 100)
    
    
  ),
  
  # Render plots -----------------
  mainPanel(renderPlot({plots_to_render_SIR()}, width = 600, height = 800))
  
)


# Run the simulation -------------------

# Set the initial population sizes
init <- reactive({c(S = input$S0, I = input$I0, R = input$R0)})
# Set the parameter values
params <- reactive({c(m = input$m, beta = input$beta, v = input$v, gamma = input$gamma)})
# Time over which to simulate model dynamics
time <- reactive({seq(0,input$time,by = .1)})

# Use the SIR function above to run 
# the SIR model using the 
# parameter estimates defined above
out <- reactive({data.frame(deSolve::ode(func = SIR,
                               y=init(), parms=params(), times = time()))})

# Reshape the data so that population sizes of both 
# species are in one column, and an extra column to define
# species name. This helps with the plotting...
out_long <- reactive({pivot_longer(out(), c(S, I, R), "group") %>% 
  mutate(group = factor(group, levels = c("S", "I", "R")))})

# use out to create dS, dI, dR, and the per capita changes in population
pop_out <- reactive({
  pop_out <- out()
  pop_out$dS <- c(NA, diff(pop_out$S))
  pop_out$dI <- c(NA, diff(pop_out$I))
  pop_out$dR <- c(NA, diff(pop_out$R))
  # not using pgrs right now but could be useful to calculate
  pop_out <- pop_out %>% mutate(pgrS = dS/S, pgrI = dI/I, pgrR = dR/R)
  pop_out
})

pop_out_long <- reactive({ pop_out() %>%
  select(time, dS, dI, dR) %>%
  pivot_longer(c(dS, dI, dR), "group") %>%
  mutate(group = factor(group, levels = c("dS", "dI", "dR")))
})

# Make plots --------------------


# Plot abundance through time ----------
abund_plot_SIR <- reactive({ggplot(out_long()) + 
    geom_line(aes(x = time, y = value, color = group), size = 2) + 
    scale_color_brewer(palette = "Set1") +
    ylab("Population size") + 
    ecoevoapps::theme_apps()
})

# Plot dS, dI, dR over time
dabund_plot_SIR <- reactive({ ggplot(pop_out_long()) +
    geom_line(aes(x = time, y = value, color = group), size = 2) +
    scale_color_brewer(palette = "Set1") +
    ylab("Change in population size") +
    ecoevoapps::theme_apps()
})

# Plot S vs I ---------
SIplot <- reactive({ggplot(out()) +
    geom_segment(x = out()$S[round(length(time()))/25], 
                 y = out()$I[round(length(time()))/25], 
                 xend = out()$S[round(length(time())/25) + 1], 
                 yend = out()$I[round(length(time())/25) + 1], 
                 arrow = arrow(length = unit(0.15, "npc"))) +
    geom_path(aes(x = S, y = I), size = 2) +
    scale_color_brewer(palette = "Set1") +
    ylab("I size") +
    xlab("S size") +
    ecoevoapps::theme_apps()})

# Plot I vs R --------------
RIplot <- reactive({ggplot(out()) +
    geom_segment(x = out()$R[round(length(time()))/25], 
                 y = out()$I[round(length(time()))/25], 
                 xend = out()$R[round(length(time())/25) + 1], 
                 yend = out()$I[round(length(time())/25) + 1], 
                 arrow = arrow(length = unit(0.15, "npc"))) +
  geom_path(aes(x = R, y = I), size = 2) +
  scale_color_brewer(palette = "Set1") +
  ylab("I size") +
  xlab("R size") +
  ecoevoapps::theme_apps()})

# Plot S vs R ------------
SRplot <- reactive({ggplot(out()) +
    geom_segment(x = out()$S[round(length(time()))/25], 
                 y = out()$R[round(length(time()))/25], 
                 xend = out()$S[round(length(time())/25) + 1], 
                 yend = out()$R[round(length(time())/25) + 1], 
                 arrow = arrow(length = unit(0.15, "npc"))) +
  geom_path(aes(x = S, y = R), size = 2) +
  scale_color_brewer(palette = "Set1") +
  ylab("R size") +
  xlab("S size") +
  ecoevoapps::theme_apps()})

# combine 2d plots
SIR_2d_plots <- reactive({
  wrap_plots(SIplot(), RIplot(), SRplot(), ncol = 3)
})


# Make a list of plots and print out plots based on which ones were requested ----

plots_to_render_SIR <- reactive({
  wrap_plots(abund_plot_SIR(), dabund_plot_SIR(), SIR_2d_plots(), nrow = 3) 
})


```

## SIS model

```{r sis app, echo=FALSE}
sidebarLayout(
  
  sidebarPanel(
    
    ### Ask user for parameter values ----
    
    #m - death/birth rate
    #beta - infection rate
    #gamma - recovery rate
    #v - vaccination rate
    
    sliderInput("m_sis", label = "Birth/Death rate:",
                min = 0, max = 1, value = .1, step = 0.1),
    
    sliderInput("beta_sis", label = "Infection rate:",
                min = 0, max = 1, value = .01, step = 0.01),
    
    sliderInput("gamma_sis", label = "Recovery rate:",
                min = 0, max = 1, value = .2, step = 0.1),
    
    
    ### Ask user for initial conditions ----
    numericInput("S0_sis", label = "Initial population size of S", min = 0, value = 100),
    numericInput("I0_sis", label = "Initial population size of I", min = 0, value = 1),
    numericInput("R0_sis", label = "Initial population size of R", min = 0, value = 0),
    
    ### Ask user for time to simulate ----
    numericInput("time_sis", label = "Time to simulate", min = 10, value = 100)
    
    
  ),
  
  # Render plots -----------------
  mainPanel(renderPlot({plots_to_render_sis()}, width = 600, height = 800))
  
)


# Run the simulation -------------------

# Set the initial population sizes
init_sis <- reactive({c(S = input$S0_sis, I = input$I0_sis)})
# Set the parameter values
params_sis <- reactive({c(m = input$m_sis, beta = input$beta_sis, gamma = input$gamma_sis)})
# Time over which to simulate model dynamics
time_sis <- reactive({seq(0, input$time_sis, by = .1)})

# Use the SIR function above to run 
# the SIR model using the 
# parameter estimates defined above
out_sis <- reactive({data.frame(deSolve::ode(func = SIS,
                               y = init_sis(), parms = params_sis(), times = time_sis()))})

# Reshape the data so that population sizes of both 
# species are in one column, and an extra column to define
# species name. This helps with the plotting...
out_long_sis <- reactive({pivot_longer(out_sis(), c(S, I), "group") %>% 
  mutate(group = factor(group, levels = c("S", "I")))})

# use out to create dS, dI, dR, and the per capita changes in population
pop_out_sis <- reactive({
  pop_out <- out_sis()
  pop_out$dS <- c(NA, diff(pop_out$S))
  pop_out$dI <- c(NA, diff(pop_out$I))
  # not using pgrs right now but could be useful to calculate
  pop_out <- pop_out %>% mutate(pgrS = dS/S, pgrI = dI/I)
  pop_out
})

pop_out_long_sis <- reactive({ pop_out_sis() %>%
  select(time, dS, dI) %>%
  pivot_longer(c(dS, dI), "group") %>%
  mutate(group = factor(group, levels = c("dS", "dI")))
})

# Make plots --------------------


# Plot abundance through time ----------
abund_plot_sis <- reactive({ggplot(out_long_sis()) + 
    geom_line(aes(x = time, y = value, color = group), size = 2) + 
    scale_color_brewer(palette = "Set1") +
    ylab("Population size") + 
    ecoevoapps::theme_apps()
})

# Plot dS, dI, dR over time
dabund_plot_sis <- reactive({ ggplot(pop_out_long_sis()) +
    geom_line(aes(x = time, y = value, color = group), size = 2) +
    scale_color_brewer(palette = "Set1") +
    ylab("Change in population size") +
    ecoevoapps::theme_apps()
})

# Plot S vs I ---------
SIplot_sis <- reactive({ggplot(out_sis()) +
    geom_segment(x = out_sis()$S[round(length(time_sis()))/25], 
                 y = out_sis()$I[round(length(time_sis()))/25], 
                 xend = out_sis()$S[round(length(time_sis())/25) + 1], 
                 yend = out_sis()$I[round(length(time_sis())/25) + 1], 
                 arrow = arrow(length = unit(0.15, "npc"))) +
    geom_path(aes(x = S, y = I), size = 2) +
    scale_color_brewer(palette = "Set1") +
    ylab("I size") +
    xlab("S size") +
    ecoevoapps::theme_apps()})



# Make a list of plots and print out plots based on which ones were requested ----

plots_to_render_sis <- reactive({
  wrap_plots(abund_plot_sis(), dabund_plot_sis(), SIplot_sis(), nrow = 3) 
})


```
